// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package marketclient

import (
	"context"

	"market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = market.Request
	Response = market.Response

	Market interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
