// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketReq) Reset() {
	*x = MarketReq{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketReq) ProtoMessage() {}

func (x *MarketReq) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketReq.ProtoReflect.Descriptor instead.
func (*MarketReq) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *MarketReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MarketReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type SymbolThumbRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CoinThumb           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolThumbRes) Reset() {
	*x = SymbolThumbRes{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolThumbRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolThumbRes) ProtoMessage() {}

func (x *SymbolThumbRes) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolThumbRes.ProtoReflect.Descriptor instead.
func (*SymbolThumbRes) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *SymbolThumbRes) GetList() []*CoinThumb {
	if x != nil {
		return x.List
	}
	return nil
}

type CoinThumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Chg           float64                `protobuf:"fixed64,6,opt,name=chg,proto3" json:"chg,omitempty"`
	Change        float64                `protobuf:"fixed64,7,opt,name=change,proto3" json:"change,omitempty"`
	Volume        float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Turnover      float64                `protobuf:"fixed64,9,opt,name=turnover,proto3" json:"turnover,omitempty"`
	LastDayClose  float64                `protobuf:"fixed64,10,opt,name=lastDayClose,proto3" json:"lastDayClose,omitempty"`
	UsdRate       float64                `protobuf:"fixed64,11,opt,name=usdRate,proto3" json:"usdRate,omitempty"`
	BaseUsdRate   float64                `protobuf:"fixed64,12,opt,name=baseUsdRate,proto3" json:"baseUsdRate,omitempty"`
	Zone          float64                `protobuf:"fixed64,13,opt,name=zone,proto3" json:"zone,omitempty"`
	DataTime      int64                  `protobuf:"varint,14,opt,name=dataTime,proto3" json:"dataTime,omitempty"`
	Trend         []float64              `protobuf:"fixed64,15,rep,packed,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinThumb) Reset() {
	*x = CoinThumb{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinThumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinThumb) ProtoMessage() {}

func (x *CoinThumb) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinThumb.ProtoReflect.Descriptor instead.
func (*CoinThumb) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *CoinThumb) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CoinThumb) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CoinThumb) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CoinThumb) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CoinThumb) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CoinThumb) GetChg() float64 {
	if x != nil {
		return x.Chg
	}
	return 0
}

func (x *CoinThumb) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *CoinThumb) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CoinThumb) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *CoinThumb) GetLastDayClose() float64 {
	if x != nil {
		return x.LastDayClose
	}
	return 0
}

func (x *CoinThumb) GetUsdRate() float64 {
	if x != nil {
		return x.UsdRate
	}
	return 0
}

func (x *CoinThumb) GetBaseUsdRate() float64 {
	if x != nil {
		return x.BaseUsdRate
	}
	return 0
}

func (x *CoinThumb) GetZone() float64 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *CoinThumb) GetDataTime() int64 {
	if x != nil {
		return x.DataTime
	}
	return 0
}

func (x *CoinThumb) GetTrend() []float64 {
	if x != nil {
		return x.Trend
	}
	return nil
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x06market\"3\n" +
	"\tMarketReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"7\n" +
	"\x0eSymbolThumbRes\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.market.CoinThumbR\x04list\"\xf7\x02\n" +
	"\tCoinThumb\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x10\n" +
	"\x03chg\x18\x06 \x01(\x01R\x03chg\x12\x16\n" +
	"\x06change\x18\a \x01(\x01R\x06change\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12\x1a\n" +
	"\bturnover\x18\t \x01(\x01R\bturnover\x12\"\n" +
	"\flastDayClose\x18\n" +
	" \x01(\x01R\flastDayClose\x12\x18\n" +
	"\ausdRate\x18\v \x01(\x01R\ausdRate\x12 \n" +
	"\vbaseUsdRate\x18\f \x01(\x01R\vbaseUsdRate\x12\x12\n" +
	"\x04zone\x18\r \x01(\x01R\x04zone\x12\x1a\n" +
	"\bdataTime\x18\x0e \x01(\x03R\bdataTime\x12\x14\n" +
	"\x05trend\x18\x0f \x03(\x01R\x05trend2K\n" +
	"\x06Market\x12A\n" +
	"\x14FindSymbolThumbTrend\x12\x11.market.MarketReq\x1a\x16.market.SymbolThumbResB\n" +
	"Z\b./marketb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_market_proto_goTypes = []any{
	(*MarketReq)(nil),      // 0: market.MarketReq
	(*SymbolThumbRes)(nil), // 1: market.SymbolThumbRes
	(*CoinThumb)(nil),      // 2: market.CoinThumb
}
var file_market_proto_depIdxs = []int32{
	2, // 0: market.SymbolThumbRes.list:type_name -> market.CoinThumb
	0, // 1: market.Market.FindSymbolThumbTrend:input_type -> market.MarketReq
	1, // 2: market.Market.FindSymbolThumbTrend:output_type -> market.SymbolThumbRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
