// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package server

import (
	"context"
	"grpc-common/market/types/rate"
	"market/internal/logic"
	"market/internal/svc"
)

type ExchangeRateServer struct {
	svcCtx *svc.ServiceContext
	rate.UnimplementedExchangeRateServer
}

func NewExchangeRateServer(svcCtx *svc.ServiceContext) *ExchangeRateServer {
	return &ExchangeRateServer{
		svcCtx: svcCtx,
	}
}

func (s *ExchangeRateServer) UsdRate(ctx context.Context, in *rate.RateReq) (*rate.RateResp, error) {
	l := logic.NewExchangeRateLogic(ctx, s.svcCtx)
	return l.UsdRate(in)
}
