// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: register.proto

package ucclient

import (
	"context"
	"grpc-common/ucenter/types/login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq  = login.LoginReq
	LoginResp = login.LoginResp

	Register interface {
		Login(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) Login(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	client := login.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
