// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: rate.proto

package rate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateReq) Reset() {
	*x = RateReq{}
	mi := &file_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateReq) ProtoMessage() {}

func (x *RateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateReq.ProtoReflect.Descriptor instead.
func (*RateReq) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{0}
}

func (x *RateReq) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *RateReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResp) Reset() {
	*x = RateResp{}
	mi := &file_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResp) ProtoMessage() {}

func (x *RateResp) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResp.ProtoReflect.Descriptor instead.
func (*RateResp) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{1}
}

func (x *RateResp) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_rate_proto protoreflect.FileDescriptor

const file_rate_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rate.proto\x12\x04rate\"-\n" +
	"\aRateReq\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x1e\n" +
	"\bRateResp\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate28\n" +
	"\fExchangeRate\x12(\n" +
	"\ausdRate\x12\r.rate.RateReq\x1a\x0e.rate.RateRespB\bZ\x06./rateb\x06proto3"

var (
	file_rate_proto_rawDescOnce sync.Once
	file_rate_proto_rawDescData []byte
)

func file_rate_proto_rawDescGZIP() []byte {
	file_rate_proto_rawDescOnce.Do(func() {
		file_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_proto_rawDesc), len(file_rate_proto_rawDesc)))
	})
	return file_rate_proto_rawDescData
}

var file_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rate_proto_goTypes = []any{
	(*RateReq)(nil),  // 0: rate.RateReq
	(*RateResp)(nil), // 1: rate.RateResp
}
var file_rate_proto_depIdxs = []int32{
	0, // 0: rate.ExchangeRate.usdRate:input_type -> rate.RateReq
	1, // 1: rate.ExchangeRate.usdRate:output_type -> rate.RateResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rate_proto_init() }
func file_rate_proto_init() {
	if File_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_proto_rawDesc), len(file_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_proto_goTypes,
		DependencyIndexes: file_rate_proto_depIdxs,
		MessageInfos:      file_rate_proto_msgTypes,
	}.Build()
	File_rate_proto = out.File
	file_rate_proto_goTypes = nil
	file_rate_proto_depIdxs = nil
}
