// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(handler *Routers, serverCtx *svc.ServiceContext) {
	register := NewRegisterHandler(serverCtx)

	registerGroup := handler.Group()
	registerGroup.Get("/uc/register/phone", register.Register)
	registerGroup.Post("/uc/mobile/code", register.SendCode)
}
