// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"context"
	"market-api/internal/svc"
)

func RegisteHandlers(handler *Routers, serverCtx *svc.ServiceContext) {
	rate := NewExchangeRateHandler(context.Background(), serverCtx)
	registerGroup := handler.Group()
	registerGroup.Post("/exchange-rate/usd/:unit", rate.UsdRate)

}
